project:
  type: website
  output-dir: docs

website:
  title: "KrorngAI"

format:
  html:
    linkcolor: "black"
    mainfont: "JetBrainsMono Nerd Font"
    theme: cosmo
    css: styles.css
    toc: true

