project:
  type: website
  output-dir: docs

website:
  title: "KrorngAI"

format:
  html:
    linkcolor: "blue"
    mainfont: "Gill Sans"
    fontsize: 22px
    theme: cosmo
    css: styles.css
    toc: true

