project:
  type: website
  output-dir: docs

website:
  title: "ក្រង AI"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

format:
  html:
    linkcolor: "blue"
    mainfont: "Gill Sans"
    fontsize: 22px
    theme: flatly
    css: styles.css
    toc: true

